services:
  backend:
    container_name: backend
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=Host=cloDB;Port=5432;Database=clothingDB;Username=postgres;Password=1234
    ports:
      - 3000:3000
    depends_on:
      cloDB:
        condition: service_healthy
    networks:
      - app-network
  cloDB:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clothingDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clothingDB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local
  opensearch_data:
    driver: local